### ISSUE TITLE
请问大佬JDCAX6600的固件找不到了

### ISSUE THREAD

**Issue by Twilight1911** [VIKINGYFY/OpenWRT-CI#101]
这两天早上蹲守更新发现没有ax6600了，请问是名称改了吗，感谢大佬们。

**Comment by YGQ8988** [comment]
> 这两天早上蹲守更新发现没有ax6600了，请问是名称改了吗，感谢大佬们。

应该是改名了，亚瑟ax1800pro，大佬命名是：jdcloud_re-ss-01，你自己搜下吧

**Comment by VIKINGYFY** [comment]
换名字了，01亚瑟，02雅典娜，03百里，07太乙
