### ISSUE TITLE
固件SSH默认连不上

### ISSUE THREAD

**Issue by qqsir-dev** [VIKINGYFY/OpenWRT-CI#104]
需要在设置SSH访问那里点一下保存并应用，什么都不用改，就点一下按钮然后就可以连接了
这个要改哪里或者加什么命令？
我试了下列
/etc/init.d/dropbear restart 或者 /etc/init.d/dropbear enable 都不起作用

**Comment by VIKINGYFY** [comment]
重启一下路由器
