### ISSUE TITLE
ZyXEL EX5700 (Telenor),Wifi in 6GHz mode does not work

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/OpenWRT-CI#106]
ZyXEL EX5700 (Telenor), you can add the option of 6ghz wifi with additional selection of 5ghz or 6ghz band... ZyXEL EX5700 (Telenor). When I turn it on in the mode as shown in the picture, the laptop and phone cannot find it. Wifi in 6GHz mode does not work. Can anyone tell me how to change it to 5GHz mode for it to work? Thank you.
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/
![Screenshot (897)](https://github.com/user-attachments/assets/0d23f215-7280-49f5-acf9-f68cf481b687)

**Comment by VIKINGYFY** [comment]
WIFI country chang to the US，try it

**Comment by Doanduy09** [comment]
> Nước WIFI đổi sang Mỹ, thử xem

i switched to us region like it doesnt work

**Comment by VIKINGYFY** [comment]
please use CloseWRT firmware, 6G support is very good.
https://github.com/VIKINGYFY/CloseWRT-CI/tags
