### ISSUE TITLE
redmi_ax5_jdcloud带wifi的版本无法启动

### ISSUE THREAD

**Issue by shookgao** [VIKINGYFY/OpenWRT-CI#107]
大佬，不带wifi的版本刷了后能正常启动，但带wifi的版本刷了会不停的重启，是不是有什么BUG？

**Comment by VIKINGYFY** [comment]
贴个TTL日志，不然没法算卦

**Comment by shookgao** [comment]
没弄过TTL，只能暂时放弃了

**Comment by VIKINGYFY** [comment]
是你自己编译的还是直接刷我的？

**Comment by shookgao** [comment]
直接刷的你的，测试没问题才会fork到我那边去，所以现在我那边只用了wifi_no的配置

**Comment by VIKINGYFY** [comment]
package/firmware/ath11k-firmware/Makefile，改成上游的版本，编译试一下

**Comment by shookgao** [comment]
我不知道怎么改成上游版本，但是我刚才用fork过去的版本自己编译了一个，可以正常刷机，搞不懂昨天从你这儿下的那个为什么会有问题，也许只是简单的编译过程出了点问题？感觉你的脚本本身应该是没有问题的

**Comment by shookgao** [comment]
搞不懂了，这次编译的WIFI_YES没问题了，但是WIFI_NO又不行了，两个的编译选项几乎是一模一样的啊

**Comment by VIKINGYFY** [comment]
好神奇，再看看

**Comment by shookgao** [comment]
不知道是不是同时编译多个镜像的问题，我现在把它拆成两个任务，好像没有问题了
