### ISSUE TITLE
莫名多出了个 utun 接口

### ISSUE THREAD

**Issue by baopengsun** [VIKINGYFY/OpenWRT-CI#13]
大侠好！ 首先感谢您编写的OP编译脚本！我近日用您的脚本编译的X64固件发现“网络设置”中莫名多了一个 UTUN接口 ，今天下载您编译的X64固件发现“网络设置”里也多了一个 UTUN接口  ……  烦请大侠明察 告知 UTUN接口的用处，再次的感谢大侠！！

**Comment by VIKINGYFY** [comment]
openclash的TUN模式接口

**Comment by baopengsun** [comment]
感谢大侠的回复！冒昧的多问一句怎么以前用openclash没有此接口， 此接口有什么新功能 ？ …… 再次的感谢！

**Comment by VIKINGYFY** [comment]
过滤OC流量的
