### ISSUE TITLE
为啥一直报这个错误

### ISSUE THREAD

**Issue by love-dy** [VIKINGYFY/OpenWRT-CI#14]
![1](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/4d0df68d-8f59-473f-87e7-c8b069d3683d)

**Comment by love-dy** [comment]
![image](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/dbae5723-310e-4729-96dd-6e1f5afbe9e0)

**Comment by love-dy** [comment]
大佬, 问题出在哪呢

**Comment by love-dy** [comment]
![image](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/7cb46702-a6f8-4e71-a931-ac27302fa906)

**Comment by VIKINGYFY** [comment]
LEDE源码的锅，等大雕修复

**Comment by love-dy** [comment]
非常感谢大佬指点, 现在可以编译了
