### ISSUE TITLE
用 immortalwrt源码编译OP出错

### ISSUE THREAD

**Issue by baopengsun** [VIKINGYFY/OpenWRT-CI#15]
大侠好！ 我这几天用自动编译脚本（immortalwrt源码）编译OP老是出错，提示：“You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 56 MB” …… 烦请大侠指点迷津！ 
![SBP2023-10-09 15 54 13](https://github.com/VIKINGYFY/OpenWRT-CI/assets/14248777/4dfacc80-1c3a-4d4f-b501-852767da968e)

**Comment by baopengsun** [comment]
奇怪的是用另一自动脚本（ LEDE源码 ）每天可以正常编译 ……

**Comment by VIKINGYFY** [comment]
重新拉取或者同步我的项目，估计是你哪里没改对
