### ISSUE TITLE
关于 360t7 的刷机方式

### ISSUE THREAD

**Issue by gzxiexl** [VIKINGYFY/OpenWRT-CI#17]
目前我刷入的 uboot 是来自：https://github.com/hanwckf/bl-mt798x

之前在恩山下的固件都有 108m 的字样，请问下您的固件，lede 或 immort 的两个 360t7都有固件，我的这个uboot都能刷不？ 担心变砖，先问问，谢谢

**Comment by VIKINGYFY** [comment]
先更新这里的[UBOOT](https://github.com/VIKINGYFY/UBOOT-CI/releases)，然后再刷即可
