### ISSUE TITLE
刷了固件无法引导

### ISSUE THREAD

**Issue by gj0518** [VIKINGYFY/OpenWRT-CI#2]
r4s的固件刷了之后无法引导，有什么办法吗

**Comment by VIKINGYFY** [comment]
请用今天早上的包卡刷，lede源昨晚刚撤回了uboot相关的改动

**Comment by gj0518** [comment]
> 请用今天早上的包卡刷，lede源昨晚刚撤回了uboot相关的改动
请问L-WRT和L-wrt什么区别

**Comment by VIKINGYFY** [comment]
> > 请用今天早上的包卡刷，lede源昨晚刚撤回了uboot相关的改动
> > 请问L-WRT和L-wrt什么区别

L-WRT是lede源，I-WRT是imm源

**Comment by gj0518** [comment]
> > > 请用今天早上的包卡刷，lede源昨晚刚撤回了uboot相关的改动
> > > 请问L-WRT和L-wrt什么区别
> 
> L-WRT是lede源，I-WRT是imm源

这两天的版本都刷了，还是引导不了，sys灯常亮，别的灯不亮，求解

**Comment by VIKINGYFY** [comment]
> > > > 请用今天早上的包卡刷，lede源昨晚刚撤回了uboot相关的改动
> > > > 请问L-WRT和L-wrt什么区别
> > 
> > 
> > L-WRT是lede源，I-WRT是imm源
> 
> 这两天的版本都刷了，还是引导不了，sys灯常亮，别的灯不亮，求解

LEDE源的BUG，等待修复吧

**Comment by VIKINGYFY** [comment]
LEDE上游已修复RK系列无法引导的BUG。
