### ISSUE TITLE
lede源码cmcc rax3000没有固件

### ISSUE THREAD

**Issue by fun-li** [VIKINGYFY/OpenWRT-CI#20]
<img width="977" alt="image" src="https://github.com/VIKINGYFY/OpenWRT-CI/assets/57790422/bc585fc8-e613-43a6-b50b-b87cb4c01fd8">

**Comment by VIKINGYFY** [comment]
因为我是用的通用配置，所以设备列表不太准，LEDE没有适配RAX3000M，请用IMM源或者[CloseWRT-CI](https://github.com/VIKINGYFY/CloseWRT-CI)里的闭源固件

**Comment by fun-li** [comment]
感谢回复
