### ISSUE TITLE
immortalwrt添加其他科学上网插件

### ISSUE THREAD

**Issue by windmakeppcool** [VIKINGYFY/OpenWRT-CI#21]
大佬，能在immortalwrt添加下其他科学上网插件么，自带的homeproxy挺难用的，对于便宜机场经常切换节点的人很不友好

**Comment by VIKINGYFY** [comment]
我也用的便宜机场，用HP很稳啊

**Comment by windmakeppcool** [comment]
但是节点不是只能手动切换么？便宜机场的节点不得经常换吗？

**Comment by VIKINGYFY** [comment]
> 但是节点不是只能手动切换么？便宜机场的节点不得经常换吗？

暂时没有为IMM源添加其他插件的打算，你可以fork我的项目，自己添加，源已经添加好了，只需要添加配置文件即可

**Comment by Drliao2023** [comment]
大佬，方便说一下什么机场吗？
