### ISSUE TITLE
编译x86时工作流程能走完，但没有固件包，rockchip正常

### ISSUE THREAD

**Issue by love-dy** [VIKINGYFY/OpenWRT-CI#23]
你好大佬，编译x86时工作流程能走完，但没有固件包，rockchip正常编译有固件包，请问这是什么问题，把所有不必要的插件都去掉也不行，rockchip无论如何都能成功，x86就不行
![1](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/eb7e4a55-084c-4daf-a63e-bed9413bc17f)
![2](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/9adee1b6-5c4f-4a89-95f5-d6b28fef70db)
![3](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/36147f44-c289-4feb-9013-143def677d0c)

**Comment by love-dy** [comment]
配置如下，其它无改动
![1](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/8a968383-3305-4e3c-ac37-1dbf06fdfc4f)
![2](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/8c5eecb5-3507-4c09-907a-744f8e06e943)
![3](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/5941d451-097c-4a37-8804-b3b74068c8b3)

**Comment by love-dy** [comment]
![4](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/1024b50f-aefa-41d3-96f3-ba529e620c45)

**Comment by VIKINGYFY** [comment]
我的项目是根据Config/X64.txt里第一行来检索和修改文件的，x86_64固件名里没有包含这个，所以无法打包固件，后续我可能会修改一下

**Comment by love-dy** [comment]
我懂了，大佬，非常感谢你的指点，又学到了新知识，你的项目很好用
![1](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/14da29d0-cadd-41c4-b466-03e4316f1f6b)
![2](https://github.com/VIKINGYFY/OpenWRT-CI/assets/113014261/1d202546-ee85-474d-b05d-dc53b437f9b1)
