### ISSUE TITLE
immortalwrt.git_x86-64-generic-squashfs-combined-efi_24.02.26_04.20.57.img.gz 下载后无法解压

### ISSUE THREAD

**Issue by AlanLang** [VIKINGYFY/OpenWRT-CI#27]
十分感谢提供了如此好用的工具，最近发现 release 中的 [immortalwrt.git_x86-64-generic-squashfs-combined-efi_24.02.26_04.20.57.img.gz](https://github.com/VIKINGYFY/OpenWRT-CI/releases/download/X64_immortalwrt.git_24.02.26_04.20.57/immortalwrt.git_x86-64-generic-squashfs-combined-efi_24.02.26_04.20.57.img.gz)下载后无法解压。希望有时间的话能检查一下，十分感谢。

**Comment by VIKINGYFY** [comment]
好像不用解压就能刷吧，再说了，跟我也没关系啊，我只是编译，源码又不是我写的

**Comment by AlanLang** [comment]
好的，抱歉打扰您了
