### ISSUE TITLE
RAX3000M-emmc开启autosamba会导致无线网络无法开启

### ISSUE THREAD

**Issue by tignioj** [VIKINGYFY/OpenWRT-CI#28]
https://github.com/VIKINGYFY/OpenWRT-CI/blob/0013ef7b43547508565c26d0fed4aea89da0ef06/Config/General.txt#L15

无论是大雕还是天灵的固件，在RAX3000M-emmc设备上，开启autosamba会导致无线网络无法使用，其他机型如何？如果其他机型也是无法使用的话，建议这个配置默认改为关闭

 https://github.com/immortalwrt/immortalwrt/issues/1201

**Comment by VIKINGYFY** [comment]
谢谢反馈。暂时懒得动，因为这是上游源码的问题，我用的nand版也没发现这个问题
