### ISSUE TITLE
请问是否可以支持编译6.x内核的版本

### ISSUE THREAD

**Issue by xkrfer** [VIKINGYFY/OpenWRT-CI#4]
首先，感谢作者创建这么好的一个云编译仓库，该仓库是我见过结构目录最清晰的。

其次，请教一下，如果想编译6.x内核的版本，需要在哪里做改动呢？目前只查到需要在.config里配置LINUX_KERNEL_TESTING=y，但在本仓库是不是需要配置成CONFIG_LINUX_KERNEL_TESTING=y 呢？

**Comment by VIKINGYFY** [comment]
在配置文件里加入
CONFIG_TESTING_KERNEL=y
即可，不过目前就LEDE支持切换到6.x内核

**Comment by xkrfer** [comment]
@VIKINGYFY 谢谢！
