### ISSUE TITLE
CPU占用率很高

### ISSUE THREAD

**Issue by laomao9000** [VIKINGYFY/OpenWRT-CI#41]
刷了这个openwrt-6.x.git_zn_m2-squashfs-sysupgrade_24.07.01_04.14.45.bin，兆能M2，防火墙里面设置了流量分载，
下载千兆测试，cpu使用率到30%。
是设置问题，还是驱动问题？
谢谢！

**Comment by VIKINGYFY** [comment]
关掉流量分载，因为已经集成NSS硬件加速

**Comment by laomao9000** [comment]
谢谢指导！困惑于此

**Comment by laomao9000** [comment]
试用两天，稳定，基本完美。
测试性能，可以跑满千兆宽带，但发现硬件加速还是有问题：
防火墙开启软件offload/硬件offload，千兆测速CPU应用率在30%；
防火墙不开offload，千兆测速CPU使用率能到70以上。
另外，不显示NSS使用率.
希望能继续优化，谢谢！

**Comment by VIKINGYFY** [comment]
> 试用两天，稳定，基本完美。 测试性能，可以跑满千兆宽带，但发现硬件加速还是有问题： 防火墙开启软件offload/硬件offload，千兆测速CPU应用率在30%； 防火墙不开offload，千兆测速CPU使用率能到70以上。 另外，不显示NSS使用率. 希望能继续优化，谢谢！

老哥你咋测试的？

**Comment by laomao9000** [comment]
用测速网站https://www.speedtest.cn/，http://speedtest.im/做宽带网速测试，这边通过路由器看CPU使用率
开启防火墙offload：
![1720060920593](https://github.com/VIKINGYFY/OpenWRT-CI/assets/30372748/f4e5b664-0471-46fb-b16e-dbaea85a56ec)

关闭防火墙offload：
![微信截图_20240704104501](https://github.com/VIKINGYFY/OpenWRT-CI/assets/30372748/b0f35fba-bae7-4202-bc73-cbe4d60c41bd)

**Comment by King-Of-Knights** [comment]
@laomao9000 做两件事情：

1. 在SSH里面输入`cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi`，看看是否开启了NSS，如果显示文件不存在，就是没有正常开启；
2. 另外，确保测试是在电脑或手机上进行，不是在路由器端进行

**Comment by laomao9000** [comment]
> @laomao9000 做两件事情：
> 
> 1. 在SSH里面输入`cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi`，看看是否开启了NSS，如果显示文件不存在，就是没有正常开启；
> 2. 另外，确保测试是在电脑或手机上进行，不是在路由器端进行

 cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi
CPU Utilization:
Note: Averaged over 1 second

Core 0:
Min     Avg     Max
 4%      29%     58%

**Comment by King-Of-Knights** [comment]
@laomao9000 看起来NSS是被用起来了，你是在路由器测速，还在电脑上测速？

**Comment by VIKINGYFY** [comment]
> > @laomao9000 做两件事情：
> > 
> > 1. 在SSH里面输入`cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi`，看看是否开启了NSS，如果显示文件不存在，就是没有正常开启；
> > 2. 另外，确保测试是在电脑或手机上进行，不是在路由器端进行
> 
> 开启测速： cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi CPU Utilization: Note: Averaged over 1 second
> 
> Core 0: Min Avg Max 4% 29% 58%
> 
> 测速结束： Note: Averaged over 1 second
> 
> Core 0: Min Avg Max 4% 4% 58%

http://speedtest.im/
这个测速的时候注意选国内节点，国外节点会变成梯子测速，梯子没法用NSS加速

**Comment by laomao9000** [comment]
> @laomao9000 看起来NSS是被用起来了，你是在路由器测速，还在电脑上测速？

电脑上跑，可能这CPU/NPU就这水平哈

**Comment by VIKINGYFY** [comment]
> > @laomao9000 看起来NSS是被用起来了，你是在路由器测速，还在电脑上测速？
> 
> 电脑上跑，可能这CPU/NPU就这水平哈，千兆宽带用绰绰有余 跑分不错：
> 
> /etc/coremark.sh && cat /etc/bench.log (CpuMark : 20253.164557 Scores)

这是IPQ60XX的正常水平，还是注意下测速节点是不是国内的

**Comment by laomao9000** [comment]
这个U算力可以！所以想挖掘下。

谢谢！
