### ISSUE TITLE
关于编译时WiFi名称选项的更改

### ISSUE THREAD

**Issue by liaoke01** [VIKINGYFY/OpenWRT-CI#42]
有一些主机如r2s并没有WiFi功能,是否可以更改为wifi选项为非必需,当为空时则不执行，更改WiFi名称操作.

以及是否支持在仓库根目录新建files文件夹,启用替换大法

**Comment by VIKINGYFY** [comment]
1，改wifi名和有没有wifi不冲突
2，暂时不支持，有空看一下
