### ISSUE TITLE
请问如何加入openclash

### ISSUE THREAD

**Issue by kennyhn88** [VIKINGYFY/OpenWRT-CI#43]
看到Config/General.txt中说
增加插件，科学上网插件请在Scripts/Settings.sh调整
如果我需要openclash
请问具体该怎么操作呢 感谢

**Comment by VIKINGYFY** [comment]
默认lede源已选择oc，如果是其他源也想用，就在下面写上即可

![image](https://github.com/VIKINGYFY/OpenWRT-CI/assets/7755795/846209db-50b1-4168-bf62-2986b9021f5f)
