### ISSUE TITLE
佬，可不可以增加release出manifest列表，config文本行数太多了，菜鸡如我不太会看。

### ISSUE THREAD

**Issue by 20ssjy2871** [VIKINGYFY/OpenWRT-CI#47]
RT

**Comment by VIKINGYFY** [comment]
请告知文件具体路径和名字，因为我没有搭建本地编译，所以不好搞

**Comment by 20ssjy2871** [comment]
我问了下chatgpt，
 # 示例 Makefile 片段
manifest:
    echo "Generating manifest..."
    echo "Version: $(VERSION)" > manifest.txt
    echo "Date: $(shell date)" >> manifest.txt
    ls bin/packages > manifest.txt
 大概最下面那行是我要看的的吧 猜

**Comment by 20ssjy2871** [comment]
> 请告知文件具体路径和名字，因为我没有搭建本地编译，所以不好搞

我问了下chatgpt，
 # 示例 Makefile  ：
manifest:
    echo "Generating manifest..."
    echo "Version: $(VERSION)" > manifest.txt
    echo "Date: $(shell date)" >> manifest.txt
    ls bin/packages > manifest.txt

 大概最下面那行是我要看的的吧 猜

**Comment by VIKINGYFY** [comment]
看了没一下，没有必要，信息显示很局限
