### ISSUE TITLE
关于新的项目

### ISSUE THREAD

**Issue by liaoke01** [VIKINGYFY/OpenWRT-CI#49]
根据我的测试,github仓库具备当软件库的能力,大佬,有没有兴趣写一个,自动拉取填写的仓库软件源代码编译成ipk,然后根据https://openwrt.org/zh/docs/guide-developer/using_the_sdk中最后一行的make package/index - 构建仓库索引, 将输出目录变成一个本地的opkg源,最后将输出编译完的ipk文件目录上传到github,这样就可以直接在openwrt的opkg配置文件中填写src+自己的仓库,再弄一个自动更新,sdk的版本自由选择填写什么拉取什么的sdk,我找遍了github没有一个项目是可以自动搭建自己的软件源的,实现不是很难,不过我不太熟悉openwrt的编译流程,总是报错,大佬有没有兴趣搞一下？（造福众生,整体的逻辑和实现应该不难写

**Comment by VIKINGYFY** [comment]
过于复杂了，我玩得真没你们花

**Comment by liaoke01** [comment]
> 过于复杂了，我玩得真没你们花

其实编译好后在package目录使用make index生成索引就行了,然后把生成的目录上传到github,之后在openwrt里面把自己的仓库链接填进去，就可以直接使用软件源了,我自己编译，不知道怎么老是报错
