### ISSUE TITLE
感谢作者老哥的脚本

### ISSUE THREAD

**Issue by rianjskis** [VIKINGYFY/OpenWRT-CI#5]
请问我的机型是r2s如果想自定义插件选项是否能把我在虚拟机中选好生成的.config文件放到config/Rockchip中并生效.我在虚拟机中生成的是6.1内核在.config中能看到CONFIG_LINUX_6_1=y，生成./scripts/diffconfig.sh > diffconfig后就没有了，我在其他Issues 区中看到您说添加:CONFIG_TESTING_KERNEL=y就等于选择了6.X内核,.添加软件源的话请问添加在那个文件，以下是我的config文件以及需要添加的软件源，感谢您，

[diffconfig.txt](https://github.com/VIKINGYFY/OpenWRT-CI/files/11365374/diffconfig.txt)

echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> ./feeds.conf.default
echo "src-git small https://github.com/kenzok8/small" >> ./feeds.conf.default
git clone https://github.com/sirpdboy/luci-app-ddns-go.git package/ddns-go
git clone https://github.com/sirpdboy/luci-app-autotimeset package/luci-app-autotimeset
git clone https://github.com/natelol/luci-app-beardropper package/luci-app-beardropper
git clone https://github.com/thinktip/luci-theme-neobird.git package/luci-theme-neobird

**Comment by VIKINGYFY** [comment]
按照Plugins.sh中的格式添加插件源即可，不推荐用任何大杂烩源，冲突报错很多

**Comment by rianjskis** [comment]
> 按照Plugins.sh中的格式添加插件源即可，不推荐用任何大杂烩源，冲突报错很多

昨天添加了我上面发布的软件源，然后把虚拟机生成的.config文件覆盖到r2s的配置文件里，失败了😄

**Comment by VIKINGYFY** [comment]
> > 按照Plugins.sh中的格式添加插件源即可，不推荐用任何大杂烩源，冲突报错很多
> 
> 昨天添加了我上面发布的软件源，然后把虚拟机生成的.config文件覆盖到config/Rockchip文件里，失败了😄

自己认真看我的项目，每个文件都要按照格式添加

**Comment by rianjskis** [comment]
> > > 按照Plugins.sh中的格式添加插件源即可，不推荐用任何大杂烩源，冲突报错很多
> > 
> > 
> > 昨天添加了我上面发布的软件源，然后把虚拟机生成的.config文件覆盖到config/Rockchip文件里，失败了😄
> 
> 自己认真看我的项目，每个文件都要按照格式添加

老哥，编译成了，但是请问如果想自定义用户名得话，参考那个文件，感谢。

**Comment by VIKINGYFY** [comment]
用户名好像改不了

**Comment by rianjskis** [comment]
> 用户名好像改不了

好吧😂😂
