### ISSUE TITLE
运行一段时间uci无法加载

### ISSUE THREAD

**Issue by xiananliu** [VIKINGYFY/OpenWRT-CI#52]
![SL{8$CR 97L1}F3UCICGG 6](https://github.com/VIKINGYFY/OpenWRT-CI/assets/5202254/dec56f9c-5c8e-4cdf-9273-0bbceaa279f0)

**Comment by VIKINGYFY** [comment]
设备型号，内存大小，额外插件

**Comment by xiananliu** [comment]
> 设备型号，内存大小，额外插件

6月份的版本，ssh查看内存充足，插件就装了ddns-go、msdlite、和开启了homeproxy

**Comment by VIKINGYFY** [comment]
> > 设备型号，内存大小，额外插件
> 
> 6月份的版本，ssh查看内存充足，插件就装了ddns-go、msdlite、和开启了homeproxy

你这回复了跟没回复一样，关键信息都没有

**Comment by xiananliu** [comment]
这个版本 24.06.27_04.18.37

**Comment by xiananliu** [comment]
内存大小512m
