### ISSUE TITLE
upnp 重启后失效

### ISSUE THREAD

**Issue by xiananliu** [VIKINGYFY/OpenWRT-CI#54]
![image](https://github.com/VIKINGYFY/OpenWRT-CI/assets/5202254/514bf3cd-10b8-42c4-b6cf-b50c1ad5c178)
upnp只要重启就失效，必须重新启动

**Comment by xiananliu** [comment]
版本：OpenWRT-CI-24.07.10_12.21.56

**Comment by VIKINGYFY** [comment]
我的项目仅回复编译相关的问题，其他问题请直接到对应上游提交。
