### ISSUE TITLE
能否编译kmod-wireguard？

### ISSUE THREAD

**Issue by www78814** [VIKINGYFY/OpenWRT-CI#59]
固件无kmod-wireguard，opkg安装wireguard工具提示所有源都没有kmod-wireguard。
![703d351e-bf52-4eb6-a426-b08f34b5ac4a](https://github.com/user-attachments/assets/2e8228f5-e914-47f2-b14f-71fc6deecb11)

**Comment by VIKINGYFY** [comment]
4776b106007a8f8539813d92ab2c9a19f8c39694
