### ISSUE TITLE
京东云雅典娜无法使用rndis

### ISSUE THREAD

**Issue by kennyhn88** [VIKINGYFY/OpenWRT-CI#61]
用这个编译固件
我的rax3000m可以正常使用wifi棒子的网络
但是京东云雅典娜不能使用wifi棒子的网络
请问是什么原因呢

**Comment by VIKINGYFY** [comment]
雅典娜的USB问题，目前开源固件都无法驱动

**Comment by happyme531** [comment]
> 雅典娜的USB问题，目前开源固件都无法驱动

```bash
devmem 0x1016000 32 0x201 && devmem 0x1016004 32 0x2 
```
然后usb就能用了

**Comment by VIKINGYFY** [comment]
已更新dts，楼主方便的话再试试呗

**Comment by happyme531** [comment]
> 已更新dts，楼主方便的话再试试呗

实测无效

**Comment by VIKINGYFY** [comment]
> > 已更新dts，楼主方便的话再试试呗
> 
> 实测无效

那行吧，手头也没机器，等哪天捡漏买一个再折腾USB

**Comment by breeze303** [comment]
把usb的pci加上看看，驱动网络跟驱动文件传输不是一回事

**Comment by VIKINGYFY** [comment]
> 把usb的pci加上看看，驱动网络跟驱动文件传输不是一回事

B佬快点提个pr修一下

**Comment by VIKINGYFY** [comment]
USB不上电问题已修复，使用本项目编译的固件即可

**Comment by breeze303** [comment]
> USB不上电问题已修复，使用本项目编译的固件即可

我不会修
