### ISSUE TITLE
京东云亚瑟，wifi5不定时挂掉，wifi2.4没事

### ISSUE THREAD

**Issue by jmzwcn** [VIKINGYFY/OpenWRT-CI#62]
京东云亚瑟，wifi5不定时挂掉，wifi2.4没事

这个问题搞得没法用了。

**Comment by jmzwcn** [comment]
故障日志没注意，恩山论坛，几个群友反馈了。

**Comment by master-yun-yun** [comment]
我用着很好。不要装太多插件，爆内存才会丢失wifi。
本身初始剩余内存都不多，不要一股脑堆插件上去

**Comment by 363137946** [comment]
没装任何插件，一进后台很容易就重启了

**Comment by 363137946** [comment]
kucat主题也有问题

**Comment by master-yun-yun** [comment]
一通操作，目前正常了，继续观察

**Comment by master-yun-yun** [comment]
听说是8.4前的正常，9号前后的可能存在问题

**Comment by master-yun-yun** [comment]
听说是8.4前的正常，9号前后的可能存在问题

**Comment by VIKINGYFY** [comment]
感觉是patch问题，等上游修复吧

**Comment by reaichangzai** [comment]
ZN-M2的5Gwifi也会突然消失

**Comment by laiyujun** [comment]
有没有刷了网络不稳定？就是那种看电视断断续续的，说是网掉了吧他没掉，说是没掉吧看电视卡一下卡一下的，换了个系统刷就没这问题！另外一个内存统计数据不准确

**Comment by master-yun-yun** [comment]
大佬已尝试修复，今（昨）天编译的固件有人刷了试过吗？

**Comment by VIKINGYFY** [comment]
经群友测试，已正常

**Comment by master-yun-yun** [comment]
> 有没有刷了网络不稳定？就是那种看电视断断续续的，说是网掉了吧他没掉，说是没掉吧看电视卡一下卡一下的，换了个系统刷就没这问题！另外一个内存统计数据不准确

1）客户端（N1盒子）指定静态IP地址，看组播单播IPTV流畅，看IPV6源直播流畅，看网络视频，如TVBOX，像你说的，断断续续，一卡一卡的。
2）客户端（N1盒子）DHCP获取IP地址，看组播单播IPTV流畅，看IPV6源直播流畅，看网络视频，如TVBOX，流畅。
