### ISSUE TITLE
IPQ60XX-WIFI-YES_immortalwrt.git-main_24.08.21_04.30.02 没有wifi功能

### ISSUE THREAD

**Issue by crh251** [VIKINGYFY/OpenWRT-CI#66]
package: immortalwrt.git-main_jdcloud_ax1800-pro-squashfs-sysupgrade_24.08.21_04.30.02.bin

wifi设置中已开启且未隐藏，手机无法搜索出wifi信号。

**Comment by crh251** [comment]
<img width="1563" alt="image" src="https://github.com/user-attachments/assets/1c201acd-efc8-42aa-9594-f2b9efe9b879">

**Comment by VIKINGYFY** [comment]
WiFi设置：
QCA
地区CN，带宽20/80，信道11/149，功率20，开启MIMO，加密WPA2PSK，算法CCMP
