### ISSUE TITLE
系统上存在旧版 iptables 规则。 不鼓励混合使用 iptables 和 nftables 规则，这可能会导致流量过滤不完整

### ISSUE THREAD

**Issue by love-dy** [VIKINGYFY/OpenWRT-CI#67]
![image](https://github.com/user-attachments/assets/e8449a84-b22c-4af7-900b-5d6b9a45e8fd)
请问大佬，防火墙警告，这个问题该怎么解决呢
iptables-nft   nft-socket  等都安装了，不处理安全有影响吗

**Comment by VIKINGYFY** [comment]
非编译问题请到对应源码上游提问
