### ISSUE TITLE
Luci界面不显示nss

### ISSUE THREAD

**Issue by xihajim** [VIKINGYFY/OpenWRT-CI#71]
`cat /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi`显示是有nss的
但是luci界面不显示
能否进行优化一下

**Comment by VIKINGYFY** [comment]
有空再说，也没啥必要，nss固定7%占用

**Comment by breeze303** [comment]
> > 为啥喜欢看nss？你能看它热过头？还是占用过高还是占用过低
> 
> 大概是物尽其用，强迫症的爽感，你不是强迫症估计你体会不到嘿嘿嘿

我是体会不到，所以我不加代码上去嘿嘿

**Comment by VIKINGYFY** [comment]
11d9f001d463164ea26946b11a3d8828809085da

已添加
