### ISSUE TITLE
R4s 刷机无法启动

### ISSUE THREAD

**Issue by love-dy** [VIKINGYFY/OpenWRT-CI#72]
大佬，反馈一个问题，r4s固件无法运行呀，指示灯显示系统启动了，网卡获取不到ip，电脑无法打开后台管理页面，设置固定ip也打不开，偶尔重启后可以打开，但随便点一下菜单就找不到了，x86的没有问题，装在虚拟机上可以启动运行

**Comment by love-dy** [comment]
用你的脚本编译lede的固件，一切正常，可惜lede不支持r6s

**Comment by love-dy** [comment]
大佬，我自己编译的，和 用你编译的固件都是一样的情况，这两天试着编译无数次了，三方插件都屏蔽也不行，头大了

**Comment by VIKINGYFY** [comment]
去上游IMM反馈，这个不是编译问题，是上游RK3399系列出问题了
