### ISSUE TITLE
佬，空了搞个无线设备上网时间管理？管管熊孩子的手机~

### ISSUE THREAD

**Issue by 20ssjy2871** [VIKINGYFY/OpenWRT-CI#73]
RT~

**Comment by master-yun-yun** [comment]
自己安装插件不就行了？

**Comment by master-yun-yun** [comment]
> > 自己安装插件不就行了？
> 
> 哪个插件？ 链接谢谢~

Access Control ?

**Comment by 20ssjy2871** [comment]
无法运行这个，似乎防火墙功能不太行

**Sat Sep 14 18:36:05 2024 daemon.err uhttpd[5017]: sh: iptables: not found**

**Comment by VIKINGYFY** [comment]
需要支持fw4的才行，没有这个需求，暂时不会加入，有需求的请自行安装或者编译
