### ISSUE TITLE
云编译分配Ubuntu24版本时导致初始化环境失败

### ISSUE THREAD

**Issue by Yon8** [VIKINGYFY/OpenWRT-CI#87]
分配系统：

> Current runner version: '2.320.0'
> Operating System
>   Ubuntu
>   24.04.1
>   LTS

报错代码：
```
 Run docker rmi $(docker images -q)
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
Error: Process completed with exit code 1.
```
解决办法：
将CI中的Core文件修改系统版本
` runs-on: ubuntu-latest `
    修改为
`runs-on: ubuntu-22.04`

**Comment by VIKINGYFY** [comment]
看到了，一会改一下

**Comment by master-yun-yun** [comment]
之前没有因为这个版本问题出错过。
是个例还是什么原因？

**Comment by Yon8** [comment]
> 之前没有因为这个版本问题出错过。
> 是个例还是什么原因？

我的怎么运行都是24 加上docker rmi判空条件 接着运行会提示某个软件包找不到 所以24版本环境是不适合编译这个项目的 所以如果目前分配22正常编译 24会报错
