### ISSUE TITLE
How can I add LED controller to jdc ax6600

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/OpenWRT-CI#89]
How can I add LED controller to jdc ax6600, thank you

**Comment by VIKINGYFY** [comment]
Only a close-source ipk can be controlled, the author currently has no open-source plans. 
This is two TM1628A, you can write a drive control it.

**Comment by Doanduy09** [comment]
Thank you very much, I am waiting for the jdc ax6600 device to arrive and then test your github to create...

**Comment by Doanduy09** [comment]
I'm not good at writing controls for it, I hope you will support controlling this LED... because this device's LED is very beautiful... I've also searched online but no one has supported me. Thank you very much

**Comment by VIKINGYFY** [comment]
luci-app-athena-led has been added to my project.
