### ISSUE TITLE
刚刚编译的，cmiot_ax18概率性死机

### ISSUE THREAD

**Issue by qwerttvv** [VIKINGYFY/OpenWRT-CI#90]
以前内核4.x的老固件没问题，不是机器的问题

用的VIKINGYFY/immortalwrt，没有wifi也没有usb，其它没怎么动，目前的配置文件
https://raw.githubusercontent.com/qwerttvv/t6/f88275ef3d670ff03eb4018092f16083d03ff10b/config-M2-ss-xray-VIKINGYFY.cfg

试了几天了，有两次使用中死机，还有四次重启后死机，死机后手动断电再通电，下游客户端不能获取正确地址，客户端ip会变成169.254.174.210，只能进uboot重刷

使用多久死机不一定，最长使用时间不超过24小时，最短的刷完了以后刚刚弄好接口刚刚拨号上去，就死机了

重启也不是每次都死机，概率性的

因为一死就起不来了，也看不到日志，不知道为什么

本想着过来大佬这里下一个现成的试试，结果看到大佬你终止任务了，rls下边没货
https://github.com/VIKINGYFY/OpenWRT-CI/actions/runs/11424100789

这么多人用，我就怀疑我自己配置的问题，可瞅着也没什么，实在不知道如何了，过来询问下大佬

**Comment by VIKINGYFY** [comment]
fw4就别用ssrp了，用hp吧

另外，如果改过内存的话，优先考虑内存是否虚焊

**Comment by VIKINGYFY** [comment]
最近在折腾源码，你可以多刷一下测试

**Comment by VIKINGYFY** [comment]
你这机器内存多大的
