### ISSUE TITLE
升级丢失配置

### ISSUE THREAD

**Issue by 1105384898** [VIKINGYFY/OpenWRT-CI#93]
x86的固件，在pve中运行，每次升级数据就会丢失，上传之前的配置也是显示超时，大佬怎么解决

**Comment by VIKINGYFY** [comment]
没玩过这个呢，建议百度一下

**Comment by 1105384898** [comment]
> 没玩过这个呢，建议百度一下

没问题了，谢谢，一个插件一个插件的去编，发现是我加的ucky插件的问题，加进去，升级就丢数据，现在换了一个源
