### ISSUE TITLE
jdcloud ax1800pro has no Packages.gz

### ISSUE THREAD

**Issue by justinchen0330** [VIKINGYFY/OpenWRT-CI#95]
# opkg update
Downloading https://downloads.immortalwrt.org/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
*** Failed to download the package list from https://downloads.immortalwrt.org/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz

There is no Packages.gz, how can I fix it?

The issue has been found since this two fireware below:
immortalwrt.git-main_jdcloud_ax1800-pro-squashfs-factory_24.10.29_04.22.27.bin
immortalwrt.git-main_jdcloud_ax1800-pro-squashfs-sysupgrade_24.10.29_04.22.27.bin

**Comment by VIKINGYFY** [comment]
Just ignore it, because there is no link in upstream.
