### ISSUE TITLE
新版本更新了opkg为apk后网页上的配置存在问题

### ISSUE THREAD

**Issue by cmlong05** [VIKINGYFY/OpenWRT-CI#99]
![image](https://github.com/user-attachments/assets/ddf4fb6d-37e2-4311-93f6-cdbcd7f3d089)

**Comment by VIKINGYFY** [comment]
上游的锅，等修复即可

**Comment by YGQ8988** [comment]
> 上游的锅，等修复即可

到时候上游更新了就能用吗，还行需要升级固件呀，大佬！

**Comment by VIKINGYFY** [comment]
> > 上游的锅，等修复即可
> 
> 到时候上游更新了就能用吗，还行需要升级固件呀，大佬！

那肯定是得刷固件啊，又不能在线更新

**Comment by YGQ8988** [comment]
> > > 上游的锅，等修复即可
> > 
> > 
> > 到时候上游更新了就能用吗，还行需要升级固件呀，大佬！
> 
> 那肯定是得刷固件啊，又不能在线更新

但是看配置里面的URL就一个是404，：https://downloads.immortalwrt.org/snapshots/targets/qualcommax/ipq60xx/packages/packages.adb
如果这个链接修复了就可以用吧，或者能直接替换一个能用的这个连接就行吗？

**Comment by cmlong05** [comment]
这个连接一直是这个状态，导致update第一个总是报错，虽然用起来没什么问题，大佬看能不能跟上游反应一下把这个问题解决了。问下他们为什么要移除
IPQ60XX啊

**Comment by VIKINGYFY** [comment]
ipq60xx上游一直没有的
